process.env.NODE_ENV = "test";
process.env.MONGODB_URL = "mongodb://localhost:27017/just_adure_test";
process.env.JWT_ACCESS_SECRET = "test-access-secret-at-least-32-characters";
process.env.JWT_REFRESH_SECRET = "test-refresh-secret-at-least-32-characters";
process.env.PAYSTACK_PUBLIC_KEY = "pk_test_placeholder";
process.env.PAYSTACK_SECRET_KEY = "sk_test_placeholder";
process.env.BREVO_API_KEY = "brevo-placeholder";
process.env.BREVO_SENDER_EMAIL = "noreply@example.com";
process.env.BREVO_SENDER_NAME = "Just Adure Nigeria Ltd";
process.env.CLOUDINARY_CLOUD_NAME = "cloud-name-placeholder";
process.env.CLOUDINARY_API_KEY = "api-key-placeholder";
process.env.CLOUDINARY_API_SECRET = "api-secret-placeholder";
process.env.LOG_LEVEL = "silent";
export {};
