import { connectMongo, disconnectMongo } from "../config/mongo.js";
import { Brand, Category, ConditionGrade, DeliveryZone, Product, } from "../models/catalogue.js";
import { User } from "../models/user.js";
import { Order } from "../models/order.js";
import { Payment } from "../models/payment.js";
import { ReturnRequest } from "../models/return-request.js";
import { hashPassword } from "../utils/password.js";
const conditionGrades = [
    {
        code: "like_new",
        name: "Like New",
        description: "Minimal signs of use and exceptionally clean overall.",
        sortOrder: 1,
    },
    {
        code: "excellent",
        name: "Excellent",
        description: "Light cosmetic wear with no effect on normal operation.",
        sortOrder: 2,
    },
    {
        code: "very_good",
        name: "Very Good",
        description: "Clear signs of previous use but neat, reliable and fully tested.",
        sortOrder: 3,
    },
    {
        code: "good",
        name: "Good",
        description: "Visible everyday wear, fully tested and working as described.",
        sortOrder: 4,
    },
    {
        code: "fair",
        name: "Fair",
        description: "Noticeable cosmetic wear or disclosed defects, priced accordingly.",
        sortOrder: 5,
    },
];
const deliveryZones = [
    {
        code: "lagos-mainland",
        name: "Lagos Mainland",
        state: "Lagos",
        cityPattern: "Ikeja|Yaba|Surulere|Gbagada|Maryland",
        feeKobo: 7_500_00,
        minDeliveryDays: 1,
        maxDeliveryDays: 2,
        priority: 20,
    },
    {
        code: "lagos-state",
        name: "Lagos State",
        state: "Lagos",
        feeKobo: 12_000_00,
        minDeliveryDays: 1,
        maxDeliveryDays: 3,
        priority: 10,
    },
    {
        code: "abuja-fct",
        name: "Abuja FCT",
        state: "Federal Capital Territory",
        feeKobo: 18_000_00,
        minDeliveryDays: 2,
        maxDeliveryDays: 4,
        priority: 10,
    },
];
const catalogue = [
    {
        name: "Apple Desktop Computer",
        slug: "apple-desktop-computer-uk-used",
        sku: "JAD-CMP-APL-DESK-001",
        brand: "Apple",
        brandSlug: "apple",
        category: "Computers",
        categorySlug: "computers",
        condition: "excellent",
        priceKobo: 520_000_00,
        previousPriceKobo: 560_000_00,
        stockQuantity: 1,
        shortDescription: "Clean UK-used Apple desktop computer for office, school and creative work.",
        description: "Tested Apple desktop with display, storage, keyboard/mouse support, Wi-Fi and ports checked before listing.",
        visibleDefects: "Minor marks on the rear casing from normal UK use.",
        includedAccessories: "Power cable. Keyboard and mouse can be supplied where available.",
        warrantyInformation: "30-day functional warranty.",
        colour: "Silver",
        modelNumber: "Apple Desktop",
        featured: true,
        imageUrl: "/product-images/apple-desktop-1.jpeg",
        additionalImageUrls: ["/product-images/apple-desktop-2.jpeg"],
        specs: { Type: "Desktop computer", Usage: "Office, school and design", Display: "Desktop display", Status: "Tested working" },
    },
    {
        name: "Dell Monitor",
        slug: "dell-monitor-uk-used",
        sku: "JAD-CMP-DELL-MON-001",
        brand: "Dell",
        brandSlug: "dell",
        category: "Computers",
        categorySlug: "computers",
        condition: "excellent",
        priceKobo: 95_000_00,
        previousPriceKobo: 115_000_00,
        stockQuantity: 2,
        shortDescription: "UK-used Dell monitor suitable for desktop setups and CCTV display.",
        description: "Display panel, HDMI/VGA connection and power input have been checked for everyday use.",
        visibleDefects: "Light scratches on stand and rear casing.",
        includedAccessories: "Power cable.",
        warrantyInformation: "14-day functional warranty.",
        colour: "Black",
        modelNumber: "Dell LED Monitor",
        featured: false,
        imageUrl: "/product-images/dell-monitor.png",
        specs: { Type: "Monitor", Input: "HDMI/VGA depending on unit", Screen: "Wide display", Status: "Tested working" },
    },
    {
        name: "Dell Desktop Computer",
        slug: "dell-desktop-computer-uk-used",
        sku: "JAD-CMP-DELL-DESK-001",
        brand: "Dell",
        brandSlug: "dell",
        category: "Computers",
        categorySlug: "computers",
        condition: "good",
        priceKobo: 185_000_00,
        previousPriceKobo: null,
        stockQuantity: 2,
        shortDescription: "Reliable UK-used Dell desktop tower for office and home use.",
        description: "Desktop tower tested for booting, storage, USB ports, display output, network and general performance.",
        visibleDefects: "Normal casing scratches from previous use.",
        includedAccessories: "Power cable. Monitor, keyboard and mouse sold separately unless stated.",
        warrantyInformation: "30-day functional warranty.",
        colour: "Black",
        modelNumber: "Dell OptiPlex Series",
        featured: true,
        imageUrl: "/product-images/dell-desktop-computer.jpeg",
        specs: { Type: "Desktop tower", Usage: "Office and home", Ports: "USB, display and network ports", Status: "Tested working" },
    },
    {
        name: "Big Toshiba Plasma TV",
        slug: "big-toshiba-plasma-tv-uk-used",
        sku: "JAD-TV-TOS-PLS-001",
        brand: "Toshiba",
        brandSlug: "toshiba",
        category: "Televisions",
        categorySlug: "televisions",
        condition: "good",
        priceKobo: 240_000_00,
        previousPriceKobo: 275_000_00,
        stockQuantity: 1,
        shortDescription: "Large UK-used Toshiba plasma television for living room viewing.",
        description: "Screen, sound, ports and remote functions checked. Suitable for home, shop or lounge use.",
        visibleDefects: "Light marks on frame; no major screen damage noticed during test.",
        includedAccessories: "Power cable and remote where available.",
        warrantyInformation: "14-day functional warranty; screen impact excluded.",
        colour: "Black",
        modelNumber: "Toshiba Plasma TV",
        featured: true,
        imageUrl: "/product-images/big-toshiba-plasma-tv.png",
        specs: { Type: "Plasma TV", Size: "Large", Ports: "HDMI/AV depending on unit", Status: "Tested working" },
    },
    {
        name: "Big LG Plasma TV",
        slug: "big-lg-plasma-tv-uk-used",
        sku: "JAD-TV-LG-PLS-001",
        brand: "LG",
        brandSlug: "lg",
        category: "Televisions",
        categorySlug: "televisions",
        condition: "excellent",
        priceKobo: 260_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Large UK-used LG plasma television with tested display and sound.",
        description: "Panel, speaker output and input ports checked before listing.",
        visibleDefects: "Minor scuffs around the plastic frame.",
        includedAccessories: "Power cable and remote where available.",
        warrantyInformation: "14-day functional warranty; screen impact excluded.",
        colour: "Black",
        modelNumber: "LG Plasma TV",
        featured: false,
        imageUrl: "/product-images/big-lg-plasma-tv.jpeg",
        specs: { Type: "Plasma TV", Size: "Large", Usage: "Home entertainment", Status: "Tested working" },
    },
    {
        name: "Luxor Plasma TV",
        slug: "luxor-plasma-tv-uk-used",
        sku: "JAD-TV-LUX-PLS-001",
        brand: "Luxor",
        brandSlug: "luxor",
        category: "Televisions",
        categorySlug: "televisions",
        condition: "good",
        priceKobo: 210_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "UK-used Luxor plasma television for affordable home viewing.",
        description: "Display, power, sound and available inputs tested before listing.",
        visibleDefects: "Visible frame scratches from normal use.",
        includedAccessories: "Power cable.",
        warrantyInformation: "14-day functional warranty; screen impact excluded.",
        colour: "Black",
        modelNumber: "Luxor Plasma TV",
        featured: false,
        imageUrl: "/product-images/luxor-plasma-tv.jpeg",
        specs: { Type: "Plasma TV", Size: "Large", Condition: "UK-used", Status: "Tested working" },
    },
    {
        name: "Panasonic Plasma TV",
        slug: "panasonic-plasma-tv-uk-used",
        sku: "JAD-TV-PAN-PLS-001",
        brand: "Panasonic",
        brandSlug: "panasonic",
        category: "Televisions",
        categorySlug: "televisions",
        condition: "good",
        priceKobo: 225_000_00,
        previousPriceKobo: 250_000_00,
        stockQuantity: 1,
        shortDescription: "UK-used Panasonic plasma television with tested picture and audio.",
        description: "Suitable for customers who need a durable large-screen TV at a fair price.",
        visibleDefects: "Normal used marks on casing.",
        includedAccessories: "Power cable and remote where available.",
        warrantyInformation: "14-day functional warranty; screen impact excluded.",
        colour: "Black",
        modelNumber: "Panasonic Plasma TV",
        featured: false,
        imageUrl: "/product-images/panasonic-plasma-tv.jpeg",
        specs: { Type: "Plasma TV", Size: "Large", Display: "Colour screen", Status: "Tested working" },
    },
    {
        name: "Small Freezer",
        slug: "small-freezer-uk-used",
        sku: "JAD-APP-FRZ-SML-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Home Appliances",
        categorySlug: "home-appliances",
        condition: "good",
        priceKobo: 180_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Compact UK-used freezer for home or small business use.",
        description: "Cooling performance, thermostat and seal condition checked before listing.",
        visibleDefects: "Small dents and normal cosmetic wear.",
        includedAccessories: "Internal baskets or shelves where available.",
        warrantyInformation: "14-day functional warranty.",
        colour: "White",
        modelNumber: "Compact Freezer",
        featured: false,
        imageUrl: "/product-images/small-freezer.jpeg",
        specs: { Type: "Freezer", Size: "Small", Cooling: "Tested cold", Status: "Working" },
    },
    {
        name: "Big Washing and Spinning Machine",
        slug: "big-washing-and-spinning-machine-uk-used",
        sku: "JAD-APP-WASH-SPIN-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Home Appliances",
        categorySlug: "home-appliances",
        condition: "good",
        priceKobo: 230_000_00,
        previousPriceKobo: 260_000_00,
        stockQuantity: 1,
        shortDescription: "Large UK-used washing machine with tested wash and spin cycle.",
        description: "Water intake, drainage, drum movement, spin cycle and control panel tested.",
        visibleDefects: "Light scratches and marks on the body.",
        includedAccessories: "Power cable and water hose where available.",
        warrantyInformation: "14-day functional warranty.",
        colour: "White",
        modelNumber: "Washer Spinner",
        featured: true,
        imageUrl: "/product-images/washing-spinning-machine.png",
        specs: { Type: "Washing machine", Function: "Wash and spin", Capacity: "Large", Status: "Tested working" },
    },
    {
        name: "Dish Washer",
        slug: "dish-washer-uk-used",
        sku: "JAD-APP-DISH-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Home Appliances",
        categorySlug: "home-appliances",
        condition: "excellent",
        priceKobo: 280_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "UK-used dishwasher for modern kitchen convenience.",
        description: "Door seal, water cycle, spray arm, drainage and control panel checked.",
        visibleDefects: "Minor marks from previous installation.",
        includedAccessories: "Internal racks and power cable.",
        warrantyInformation: "14-day functional warranty.",
        colour: "Silver",
        modelNumber: "Freestanding Dishwasher",
        featured: false,
        imageUrl: "/product-images/dish-washer.png",
        specs: { Type: "Dishwasher", Installation: "Freestanding", Finish: "Silver", Status: "Tested working" },
    },
    {
        name: "Big Standing Fridge and Freezer",
        slug: "big-standing-fridge-and-freezer-uk-used",
        sku: "JAD-APP-FRIDGE-FRZ-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Home Appliances",
        categorySlug: "home-appliances",
        condition: "good",
        priceKobo: 420_000_00,
        previousPriceKobo: 460_000_00,
        stockQuantity: 1,
        shortDescription: "Large standing fridge freezer tested for strong cooling.",
        description: "Fridge and freezer compartments, light, thermostat, seals and compressor tested.",
        visibleDefects: "Normal side dents and light handle wear.",
        includedAccessories: "Shelves, drawers and ice tray where available.",
        warrantyInformation: "30-day functional warranty.",
        colour: "Silver",
        modelNumber: "Standing Fridge Freezer",
        featured: true,
        imageUrl: "/product-images/standing-fridge-freezer.png",
        specs: { Type: "Fridge freezer", Size: "Large standing", Cooling: "Fridge and freezer", Status: "Tested working" },
    },
    {
        name: "Hair Dryer and Steamer",
        slug: "hair-dryer-and-steamer-uk-used",
        sku: "JAD-BEAUTY-STEAMER-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Beauty Equipment",
        categorySlug: "beauty-equipment",
        condition: "good",
        priceKobo: 150_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Salon-style UK-used hair dryer and steamer equipment.",
        description: "Heating, steam output, stand movement and power controls checked before listing.",
        visibleDefects: "Light salon-use marks on stand and hood.",
        includedAccessories: "Stand and hood attachment.",
        warrantyInformation: "14-day functional warranty.",
        colour: "White",
        modelNumber: "Salon Steamer",
        featured: false,
        imageUrl: "/product-images/hair-dryer-steamer.png",
        specs: { Type: "Hair steamer", Usage: "Salon and home care", Stand: "Mobile stand", Status: "Tested working" },
    },
    {
        name: "Big Dryer",
        slug: "big-dryer-uk-used",
        sku: "JAD-APP-DRYER-BIG-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Home Appliances",
        categorySlug: "home-appliances",
        condition: "good",
        priceKobo: 260_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Large UK-used clothes dryer for laundry use.",
        description: "Heating, drum rotation, timer and control panel checked.",
        visibleDefects: "Cosmetic wear on front and side panels.",
        includedAccessories: "Power cable.",
        warrantyInformation: "14-day functional warranty.",
        colour: "White",
        modelNumber: "Large Clothes Dryer",
        featured: false,
        imageUrl: "/product-images/big-dryer.jpeg",
        specs: { Type: "Clothes dryer", Size: "Large", Function: "Drying cycle", Status: "Tested working" },
    },
    {
        name: "Medium Bicycle",
        slug: "medium-bicycle-uk-used",
        sku: "JAD-BIKE-MED-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Bicycles",
        categorySlug: "bicycles",
        condition: "good",
        priceKobo: 95_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Medium UK-used bicycle suitable for daily movement and exercise.",
        description: "Frame, tyres, brakes, seat and chain checked before listing.",
        visibleDefects: "Normal scratches on frame.",
        includedAccessories: "Bicycle only.",
        warrantyInformation: "7-day inspection warranty.",
        colour: "Black",
        modelNumber: "Medium Bicycle",
        featured: false,
        imageUrl: "/product-images/medium-bicycle.jpeg",
        specs: { Type: "Bicycle", Size: "Medium", Brakes: "Checked", Status: "Ride tested" },
    },
    {
        name: "Small Bicycle",
        slug: "small-bicycle-uk-used",
        sku: "JAD-BIKE-SML-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Bicycles",
        categorySlug: "bicycles",
        condition: "fair",
        priceKobo: 70_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Small UK-used bicycle for children or smaller riders.",
        description: "Ride condition, brakes, tyres and handlebar checked.",
        visibleDefects: "Visible scratches and signs of use.",
        includedAccessories: "Bicycle only.",
        warrantyInformation: "7-day inspection warranty.",
        colour: "Mixed",
        modelNumber: "Small Bicycle",
        featured: false,
        imageUrl: "/product-images/small-bicycle.jpeg",
        specs: { Type: "Bicycle", Size: "Small", Use: "Child or small rider", Status: "Ride tested" },
    },
    {
        name: "Pair of Speakers",
        slug: "pair-of-speakers-uk-used",
        sku: "JAD-AUD-SPK-PAIR-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Audio and Video",
        categorySlug: "audio-video",
        condition: "excellent",
        priceKobo: 85_000_00,
        previousPriceKobo: 100_000_00,
        stockQuantity: 1,
        shortDescription: "Pair of UK-used speakers for home audio setup.",
        description: "Sound output, speaker cones and cable connection tested.",
        visibleDefects: "Minor marks on speaker body.",
        includedAccessories: "Pair of speakers only unless stated.",
        warrantyInformation: "14-day functional warranty.",
        colour: "Black",
        modelNumber: "Speaker Pair",
        featured: false,
        imageUrl: "/product-images/pair-of-speakers.png",
        specs: { Type: "Speakers", Quantity: "Pair", Usage: "Home audio", Status: "Sound tested" },
    },
    {
        name: "Big DVD Player",
        slug: "big-dvd-player-uk-used",
        sku: "JAD-AV-DVD-BIG-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Audio and Video",
        categorySlug: "audio-video",
        condition: "good",
        priceKobo: 45_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "UK-used DVD player for home entertainment.",
        description: "Disc tray, playback, power and output ports checked.",
        visibleDefects: "Light scratches on top casing.",
        includedAccessories: "Power cable. Remote where available.",
        warrantyInformation: "7-day functional warranty.",
        colour: "Black",
        modelNumber: "DVD Player",
        featured: false,
        imageUrl: "/product-images/big-dvd-player.png",
        specs: { Type: "DVD player", Output: "AV/HDMI depending on unit", Media: "DVD/CD", Status: "Tested working" },
    },
    {
        name: "Toaster Machine",
        slug: "toaster-machine-uk-used",
        sku: "JAD-KIT-TOASTER-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Kitchen Appliances",
        categorySlug: "kitchen-appliances",
        condition: "good",
        priceKobo: 35_000_00,
        previousPriceKobo: null,
        stockQuantity: 1,
        shortDescription: "Compact UK-used toaster machine for quick breakfast preparation.",
        description: "Heating element, lever, timer and plug checked before listing.",
        visibleDefects: "Normal kitchen-use marks.",
        includedAccessories: "Toaster only.",
        warrantyInformation: "7-day functional warranty.",
        colour: "White",
        modelNumber: "Two-slot Toaster",
        featured: false,
        imageUrl: "/product-images/toaster-machine.png",
        specs: { Type: "Toaster", Slots: "Two", Power: "220-240V", Status: "Tested heating" },
    },
    {
        name: "8-Face Burner Cooker",
        slug: "8-face-burner-cooker-uk-used",
        sku: "JAD-KIT-BURNER-8F-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Kitchen Appliances",
        categorySlug: "kitchen-appliances",
        condition: "good",
        priceKobo: 190_000_00,
        previousPriceKobo: 220_000_00,
        stockQuantity: 1,
        shortDescription: "Large multi-burner cooker suitable for home or food business use.",
        description: "Burner points, knobs and general frame checked. Customer should inspect gas setup before use.",
        visibleDefects: "Used marks on metal surface and burner area.",
        includedAccessories: "Cooker body only unless stated.",
        warrantyInformation: "7-day inspection warranty.",
        colour: "Silver",
        modelNumber: "8-Face Burner",
        featured: false,
        imageUrl: "/product-images/eight-burner-cooker.png",
        specs: { Type: "Gas burner", Burners: "8-face", Usage: "Cooking", Status: "Inspection required" },
    },
    {
        name: "2/3 Seater Leather Chair",
        slug: "two-three-seater-leather-chair-uk-used",
        sku: "JAD-FUR-SOFA-23-001",
        brand: "Generic UK Used",
        brandSlug: "generic-uk-used",
        category: "Furniture",
        categorySlug: "furniture",
        condition: "excellent",
        priceKobo: 320_000_00,
        previousPriceKobo: 360_000_00,
        stockQuantity: 1,
        shortDescription: "Comfortable UK-used leather chair/sofa for living room or office.",
        description: "Leather surface, seat support and frame condition checked before listing.",
        visibleDefects: "Light crease marks from normal sitting use.",
        includedAccessories: "Sofa/chair only.",
        warrantyInformation: "7-day inspection warranty.",
        colour: "Brown",
        modelNumber: "2/3 Seater Leather Sofa",
        featured: true,
        imageUrl: "/product-images/sofa-chair.png",
        specs: { Type: "Leather sofa", Seats: "2/3 seater", Material: "Leather", Status: "Inspected" },
    },
];
const deprecatedDemoSkus = [
    "UKU-APL-IP13P-256-SB-001",
    "UKU-DELL-7420-I7-001",
    "UKU-SAM-TV50-CU-001",
    "UKU-SNY-PS5-DISC-001",
    "UKU-LG-FRG-260-001",
    "UKU-ANK-735-65W-001",
];
const demoUsers = [
    {
        name: "Just Adure Admin",
        email: "admin@gmail.com",
        phone: "08000000001",
        password: "123456789",
        roles: ["admin"],
        permissions: [],
    },
    {
        name: "Demo Customer",
        email: "customer@gmail.com",
        phone: "08000000002",
        password: "123456789",
        roles: ["customer"],
        permissions: [],
    },
];

async function upsertDemoUsers() {
    for (const user of demoUsers) {
        await User.findOneAndUpdate({ email: user.email }, {
            $set: {
                name: user.name,
                phone: user.phone,
                passwordHash: await hashPassword(user.password),
                roles: user.roles,
                permissions: user.permissions,
                emailVerifiedAt: new Date(),
                isActive: true,
            },
        }, { returnDocument: "after", upsert: true, runValidators: true });
    }
}
async function upsertConditionGrades() {
    const gradeByCode = new Map();
    for (const grade of conditionGrades) {
        const record = await ConditionGrade.findOneAndUpdate({ code: grade.code }, { $set: { ...grade, isActive: true } }, { returnDocument: "after", upsert: true, runValidators: true }).orFail();
        gradeByCode.set(record.code, record);
    }
    return gradeByCode;
}
async function upsertDeliveryZones() {
    for (const zone of deliveryZones) {
        await DeliveryZone.findOneAndUpdate({ code: zone.code }, { $set: { ...zone, isActive: true } }, { returnDocument: "after", upsert: true, runValidators: true });
    }
}
async function upsertCatalogue(gradeByCode) {
    await Product.updateMany({ sku: { $in: deprecatedDemoSkus } }, { $set: { isArchived: true, availability: "archived", stockQuantity: 0, reservedQuantity: 0 } });
    for (const item of catalogue) {
        const brand = (await Brand.findOneAndUpdate({ slug: item.brandSlug }, { $set: { name: item.brand, slug: item.brandSlug, isActive: true } }, { returnDocument: "after", upsert: true, runValidators: true }).orFail());
        const category = (await Category.findOneAndUpdate({ slug: item.categorySlug }, {
            $set: {
                name: item.category,
                slug: item.categorySlug,
                description: `Carefully tested UK-used ${item.category.toLowerCase()}.`,
                isActive: true,
            },
        }, { returnDocument: "after", upsert: true, runValidators: true }).orFail());
        const conditionGrade = gradeByCode.get(item.condition);
        if (!conditionGrade) {
            throw new Error(`Missing condition grade for ${item.condition}`);
        }
        await Product.findOneAndUpdate({ sku: item.sku }, {
            $set: {
                name: item.name,
                slug: item.slug,
                sku: item.sku,
                brandId: brand._id,
                categoryId: category._id,
                conditionGradeId: conditionGrade._id,
                priceKobo: item.priceKobo,
                previousPriceKobo: item.previousPriceKobo,
                stockQuantity: item.stockQuantity,
                reservedQuantity: 0,
                lowStockThreshold: 1,
                shortDescription: item.shortDescription,
                description: item.description,
                visibleDefects: item.visibleDefects,
                includedAccessories: item.includedAccessories,
                warrantyInformation: item.warrantyInformation,
                colour: item.colour,
                modelNumber: item.modelNumber,
                availability: "in_stock",
                isFeatured: item.featured,
                isArchived: false,
                seoTitle: `${item.name} | Just Adure Nigeria Ltd`,
                seoDescription: item.shortDescription,
                images: [item.imageUrl, ...(item.additionalImageUrls ?? [])].map((secureUrl, index) => ({
                    cloudinaryPublicId: index === 0 ? `demo/${item.slug}` : `demo/${item.slug}-${index + 1}`,
                    secureUrl,
                    altText: `${item.name} demonstration product photograph`,
                    sortOrder: index,
                    isPrimary: index === 0,
                })),
                specifications: Object.entries(item.specs).map(([label, value], index) => ({
                    groupName: "Key specifications",
                    label,
                    value,
                    sortOrder: index,
                })),
            },
        }, { returnDocument: "after", upsert: true, runValidators: true });
    }
}

async function upsertDemoReturnRequest() {
    const customer = await User.findOne({ email: "customer@gmail.com" }).lean();
    const product = await Product.findOne({ sku: "JAD-FUR-SOFA-23-001" }).populate("conditionGradeId").lean();
    const zone = await DeliveryZone.findOne({ code: "lagos-mainland" }).lean();
    if (!customer || !product) return;

    const item = {
        productId: product._id,
        name: product.name,
        slug: product.slug,
        sku: product.sku,
        condition: product.conditionGradeId?.name ?? "Excellent",
        imageUrl: product.images?.[0]?.secureUrl,
        unitPriceKobo: product.priceKobo,
        quantity: 1,
        lineSubtotalKobo: product.priceKobo,
    };

    const order = await Order.findOneAndUpdate({ orderNumber: "JAN-DEMO-RETURN-001" }, {
        $set: {
            orderNumber: "JAN-DEMO-RETURN-001",
            userId: customer._id,
            customer: {
                name: customer.name,
                email: customer.email,
                phone: customer.phone,
                addressLine1: "12 Demo Street",
                addressLine2: "",
                state: "Lagos",
                city: "Ikeja",
                deliveryInstructions: "Call before delivery.",
            },
            items: [item],
            subtotalKobo: product.priceKobo,
            discountKobo: 0,
            deliveryFeeKobo: 750000,
            totalKobo: product.priceKobo + 750000,
            currency: "NGN",
            deliveryZoneId: zone?._id,
            deliveryMethod: "delivery",
            paymentStatus: "successful",
            orderStatus: "return_requested",
            statusHistory: [
                { status: "paid", note: "Demo order paid successfully." },
                { status: "delivered", note: "Demo order delivered to customer." },
                { status: "return_requested", note: "Customer submitted a demo return request." },
            ],
            reservations: [],
            customerNotes: "Demo order created for testing return and refund workflow.",
            adminNotes: "Use this record to test the admin returns page.",
        },
    }, { returnDocument: "after", upsert: true, runValidators: true });

    await Payment.findOneAndUpdate({ reference: "JAD-DEMO-RETURN-PAYMENT" }, {
        $set: {
            orderId: order._id,
            orderNumber: order.orderNumber,
            reference: "JAD-DEMO-RETURN-PAYMENT",
            paystackTransactionId: "demo-transaction-001",
            amountKobo: order.totalKobo,
            currency: "NGN",
            status: "successful",
            channel: "card",
            gatewayResponse: "Demo successful payment",
            customerEmail: customer.email,
            paidAt: new Date(),
            verifiedAt: new Date(),
        },
    }, { returnDocument: "after", upsert: true, runValidators: true });

    await ReturnRequest.findOneAndUpdate({ requestNumber: "RET-DEMO-001" }, {
        $set: {
            requestNumber: "RET-DEMO-001",
            orderId: order._id,
            orderNumber: order.orderNumber,
            customerName: customer.name,
            customerEmail: customer.email,
            reason: "not_as_described",
            details: "Demo customer says the sofa has more visible marks than expected and wants admin review before refund decision.",
            items: [{ productId: product._id, sku: product.sku, name: product.name, quantity: 1 }],
            status: "requested",
            adminNote: "Inspect uploaded condition photos and confirm whether refund is approved.",
        },
        $unset: { refundAmountKobo: "", refundReference: "", refundProcessedAt: "", resolvedAt: "", resolvedBy: "" },
    }, { returnDocument: "after", upsert: true, runValidators: true });
}

async function main() {
    const catalogueOnly = process.argv.includes("--catalogue-only");
    await connectMongo(true);
    const gradeByCode = await upsertConditionGrades();
    await upsertDeliveryZones();
    await upsertCatalogue(gradeByCode);
    if (catalogueOnly) {
        console.info(`Seeded ${catalogue.length} UK-used product listings without demo account data.`);
        return;
    }
    await upsertDemoUsers();
    await upsertDemoReturnRequest();
    console.info(`Seeded ${catalogue.length} UK-used product listings, ${demoUsers.length} demo users and 1 demo return request.`);
}
main()
    .catch((error) => {
    console.error(error);
    process.exitCode = 1;
})
.finally(async () => {
    await disconnectMongo();
});

